Default: &defaults
  database: haskell-gym.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: haskell-gym_test.sqlite3
  <<: *defaults

Staging:
  database: haskell-gym_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: haskell-gym_production.sqlite3
  poolsize: 100
  <<: *defaults
